// FETCH
export const ITEMS_ARE_LOADING = 'ITEMS_ARE_LOADING';
export const ITEMS_HAVE_ERROR = 'ITEMS_HAVE_ERROR';
export const ITEMS_FETCH_SUCCESS = 'ITEMS_FETCH_SUCCESS';

// DRAWER
export const IS_DRAWER_OPEN = 'IS_DRAWER_OPEN';
